"""init

Revision ID: 605cc2384810
Revises:
Create Date: 2026-02-19 08:50:56.254630

"""  # noqa: INP001

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = "605cc2384810"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_banchopy_api_api_keys",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
        sa.Column("key", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("owner_id", sa.BigInteger(), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["lazer_users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_plugin_banchopy_api_api_keys_key"), "plugin_banchopy_api_api_keys", ["key"], unique=False)
    op.create_index(
        op.f("ix_plugin_banchopy_api_api_keys_name"), "plugin_banchopy_api_api_keys", ["name"], unique=False
    )
    op.create_index(
        op.f("ix_plugin_banchopy_api_api_keys_owner_id"), "plugin_banchopy_api_api_keys", ["owner_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("plugin_banchopy_api_api_keys")
    # ### end Alembic commands ###
