"""init: migrate from g0v0-server

Revision ID: 3255fe86b9cb
Revises:
Create Date: 2026-02-19 08:14:11.874040

"""  # noqa: INP001

from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "3255fe86b9cb"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plugin_beatmap_policy_allowed_beatmaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beatmap_id", sa.Integer(), nullable=False),
        sa.Column(
            "gamemode",
            sa.Enum(
                "OSU",
                "TAIKO",
                "FRUITS",
                "MANIA",
                "OSURX",
                "OSUAP",
                "TAIKORX",
                "FRUITSRX",
                "SENTAKKI",
                "TAU",
                "RUSH",
                "HISHIGATA",
                "SOYOKAZE",
                name="gamemode",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_allowed_beatmaps_beatmap_id_gamemode",
        "plugin_beatmap_policy_allowed_beatmaps",
        ["beatmap_id", "gamemode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_beatmap_policy_allowed_beatmaps_beatmap_id"),
        "plugin_beatmap_policy_allowed_beatmaps",
        ["beatmap_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_beatmap_policy_allowed_beatmaps_gamemode"),
        "plugin_beatmap_policy_allowed_beatmaps",
        ["gamemode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_beatmap_policy_allowed_beatmaps_id"),
        "plugin_beatmap_policy_allowed_beatmaps",
        ["id"],
        unique=False,
    )
    op.create_table(
        "plugin_beatmap_policy_blocked_beatmaps",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("beatmap_id", sa.Integer(), nullable=False),
        sa.Column(
            "gamemode",
            sa.Enum(
                "OSU",
                "TAIKO",
                "FRUITS",
                "MANIA",
                "OSURX",
                "OSUAP",
                "TAIKORX",
                "FRUITSRX",
                "SENTAKKI",
                "TAU",
                "RUSH",
                "HISHIGATA",
                "SOYOKAZE",
                name="gamemode",
            ),
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_blocked_beatmaps_beatmap_id_gamemode",
        "plugin_beatmap_policy_blocked_beatmaps",
        ["beatmap_id", "gamemode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_beatmap_policy_blocked_beatmaps_beatmap_id"),
        "plugin_beatmap_policy_blocked_beatmaps",
        ["beatmap_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_beatmap_policy_blocked_beatmaps_gamemode"),
        "plugin_beatmap_policy_blocked_beatmaps",
        ["gamemode"],
        unique=False,
    )
    op.create_index(
        op.f("ix_plugin_beatmap_policy_blocked_beatmaps_id"),
        "plugin_beatmap_policy_blocked_beatmaps",
        ["id"],
        unique=False,
    )

    conn = op.get_bind()
    inspector = sa.inspect(conn)
    if "banned_beatmaps" in inspector.get_table_names():
        banned_beatmaps = conn.execute(sa.text("SELECT beatmap_id FROM banned_beatmaps")).fetchall()

        if banned_beatmaps:
            for row in banned_beatmaps:
                conn.execute(
                    sa.text(
                        "INSERT INTO plugin_beatmap_policy_blocked_beatmaps "
                        "(beatmap_id, gamemode) VALUES (:beatmap_id, NULL)"
                    ),
                    {"beatmap_id": row[0]},
                )

        op.drop_table("banned_beatmaps")

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    op.create_table(
        "banned_beatmaps",
        sa.Column("id", sa.Integer(), nullable=False, autoincrement=True),
        sa.Column("beatmap_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_banned_beatmaps_beatmap_id", "banned_beatmaps", ["beatmap_id"], unique=False)

    conn = op.get_bind()
    blocked_beatmaps = conn.execute(
        sa.text("SELECT DISTINCT beatmap_id FROM plugin_beatmap_policy_blocked_beatmaps")
    ).fetchall()
    if blocked_beatmaps:
        for row in blocked_beatmaps:
            conn.execute(
                sa.text("INSERT INTO banned_beatmaps (beatmap_id) VALUES (:beatmap_id)"),
                {"beatmap_id": row[0]},
            )

    op.drop_index(
        op.f("ix_plugin_beatmap_policy_blocked_beatmaps_id"), table_name="plugin_beatmap_policy_blocked_beatmaps"
    )
    op.drop_index(
        op.f("ix_plugin_beatmap_policy_blocked_beatmaps_gamemode"), table_name="plugin_beatmap_policy_blocked_beatmaps"
    )
    op.drop_index(
        op.f("ix_plugin_beatmap_policy_blocked_beatmaps_beatmap_id"),
        table_name="plugin_beatmap_policy_blocked_beatmaps",
    )
    op.drop_index("idx_blocked_beatmaps_beatmap_id_gamemode", table_name="plugin_beatmap_policy_blocked_beatmaps")
    op.drop_table("plugin_beatmap_policy_blocked_beatmaps")
    op.drop_index(
        op.f("ix_plugin_beatmap_policy_allowed_beatmaps_id"), table_name="plugin_beatmap_policy_allowed_beatmaps"
    )
    op.drop_index(
        op.f("ix_plugin_beatmap_policy_allowed_beatmaps_gamemode"), table_name="plugin_beatmap_policy_allowed_beatmaps"
    )
    op.drop_index(
        op.f("ix_plugin_beatmap_policy_allowed_beatmaps_beatmap_id"),
        table_name="plugin_beatmap_policy_allowed_beatmaps",
    )
    op.drop_index("idx_allowed_beatmaps_beatmap_id_gamemode", table_name="plugin_beatmap_policy_allowed_beatmaps")
    op.drop_table("plugin_beatmap_policy_allowed_beatmaps")
    # ### end Alembic commands ###
